[package]
name = "test-recall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gflags = "0.3.12"
bbqvec = {path = "../../"}
anyhow = "1.0.86"
